### ISSUE TITLE
[12.8~9] 작업보고

### ISSUE THREAD

**Issue by seyoung8239** [boostcampwm-2022/web14-interface#160]
# DONE

- Landing에서 로그아웃 이후 라우팅 문제
- interviewee, interviewer, waiting 페이지 간단한 디자인
- docsList, docsItem fetch 로직 추가
- docsList, docsItem 모달 추가
    - 데이터 fetch, 레이아웃만 대충 잡아놓음
- cleanup interview, room
- 그 외 수 많은 버그 수정...
- 리팩토링

# ASK (해주세요..)

## FE

-  ~~interview docs item / list 모달 고도화~~
- ~~docs fetch할때 깜빡거림 문제~~
    - ~~Modal쪽에 Suspense 추가하는거 어떨까요~~
- axios 추상화
- ~~방에 다른 사람이 나갔을 때 stream clear해주는 로직~~
- 아래 BE 이슈 토의 후 반영

### interview docs 목록조회 API

- ~~시간순으로 정렬해서 보내주시면 더 좋을 것 같습니다.~~

### interview docs 개별조회 API

- ~~**면접관이 여러명일때 피드백들이 구분되지 않고 병합되어 return 되는 것 같습니다**~~
    - ~~nickname도 조회할 때마다 계속 바뀌네요~~
- ~~응답에 video URL이 없습니다~~
- ~~docs_uuid가 아닌 user_uuid로 조회해야 하지 않을까요?~~
    - ~~Landing에서 불러올 때 본인 기록만 불러와야 됨~~
- ~~feedback에 id도 추가 가능할까요? 랜더링할 때 필요해요ㅜ(취소)~~
- ~~createdAt Date타입이 아닌 string으로 오더라구요~~
    - ~~일단 `new Date(createdAt)`으로 해결했습니다~~

**Comment by bh2980** [comment]
* createdAt Date타입이 아닌 string으로 오더라구요
  일단 new Date(createdAt)으로 해결했습니다

이 부분은 BE와 협의가 완료된 사항입니다. 제가 미처 말씀을 못 드렸네요.

**Comment by AnJeongMin** [comment]
```
docs_uuid가 아닌 user_uuid로 조회해야 하지 않을까요?
Landing에서 불러올 때 본인 기록만 불러와야 됨
```

이건 어떤 의미인가요? 개별 조회 api가 아니라 docs 목록 조회 api 말씀하신 것 같은데
해당 api는 userId에 optional로 roomid 기반으로 조회하고 있습니다.

**Comment by AnJeongMin** [comment]
```
면접관이 여러명일때 피드백들이 구분되지 않고 병합되어 return 되는 것 같습니다
nickname도 조회할 때마다 계속 바뀌네요
```

![image](https://user-images.githubusercontent.com/74178065/206842276-26c6a0f0-c338-4335-9d94-5d853d6b7aac.png)

해당 이슈도 사진처럼 받아지는 것 확인 했는데 어떤 경우에 문제가 생기던가요?

그리고 nickname은 현재 계속 바뀌는게 맞는데 고정한 채로 보여지는게 나은가요? 
nickname 생성 로직을 조회할 때 하고 있는데 저장할 때로 이동시키면 되기는 합니다.

**Comment by AnJeongMin** [comment]
```
feedback에 id도 추가 가능할까요? 랜더링할 때 필요해요ㅜ
```
이거는 수정 하겠슴다

**Comment by bh2980** [comment]
axios 제외하고 와료했습니다.
axios는  별도의 이슈가 있는 관계로 닫겠습니다.
