### ISSUE TITLE
FE - FeedbackArea 컴포넌트 FATextArea 추출

### ISSUE THREAD

**Issue by seyoung8239** [boostcampwm-2022/web14-interface#17]
## As-Is
- FAScrollView와 FATextArea가 같은 컴포넌트에 존재한다.
- FATextArea는 제어컴포넌트라 해당 컴포넌트에 state를 지정해 주어야 한다.
  - input 상태에 대한 응집도가 떨어진다. 
- FATextArea의 input이 변경될 때마다 FeedbackArea 전체가 리렌더링 된다.
```
// Feedback.tsx - 페이지
const Feedback = () => {
  const [inputValue, setInputValue] = useState('');
  ...
  return (
    <FeedbackArea>
      ...
      	<FeedbackArea.FATextArea
		value={inputValue}
		onChange={(e) => setInputValue(e.target.value)}
	/>
    </FeedbackArea>
  )
};
```

## To-Be
- FAScrollView와 FATextArea의 분리
  - FeedbackArea 컴포넌트의 재사용성 유지

**Comment by bh2980** [comment]
비지니스 로직을 UI와 분리하여 위로 올리면서 상태들이 피드백 페이지에서 정의되어 불필요한 리렌더링이 발생하는 것 같습니다.
textarea 외에도 currentTime이 변경될 때, feedbackList가 변경될 때로 페이지 전체가 불필요하게 리렌더링 될 것 같아요.

일단 본 이슈에서는 TextArea를 @shared로 분리하고 FeedbackList를 위한 FeedbackTextArea를 별도로 정의하여 해결하겠습니다.
그 외의 currentTime이나 feedbackList 상태를 어떻게 분리할지는 별도로 이슈를 발행해두겠습니다.
